// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto_caldas.Data;

#nullable disable

namespace proyecto_caldas.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyecto_caldas.Models.usuariomodel", b =>
                {
                    b.Property<int>("Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Usuario_Id"));

                    b.Property<string>("Usuario_Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Usuario_Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
